version: '3'

services:

  live2vod:
    image: pierrezemb/gostatic
    ports:
      - 8043:8043
    volumes:
      - ./om-dvr/dist:/srv/http
    entrypoint: "/goStatic --fallback /index.html"

  admin-legacy:
    image: pierrezemb/gostatic
    volumes:
      - ./telesur-admin-legacy:/srv/http

  # kaltura:
  #   build: ./kaltura
  #   ports:
  #     - 80

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    environment:
      ALLOWED_DOMAINS: '*.tlsur.net, *.openmultimedia.biz, *.omedia.io'
      SITES: 'admin.tlsur.net=admin-legacy:8043; live2vod.openmultimedia.biz=live2vod:8043; dvr-backend.omedia.io:docker-highcpu.openmultimedia.biz:4010'
      FORCE_HTTPS: 'false'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./server-proxy.conf:/usr/local/openresty/nginx/conf/server-proxy.conf
    depends_on:
      - admin-legacy
      - live2vod

volumes:
  ssl_data: