version: '3'

services:

  live2vod:
    image: pierrezemb/gostatic
    ports:
      - 8043:8043
    volumes:
      - ./om-dvr/dist:/srv/http
    entrypoint: "/goStatic --fallback /index.html"

  admin-legacy:
    image: pierrezemb/gostatic
    volumes:
      - ./telesur-admin-legacy:/srv/http

  # kaltura:
  #   build: ./kaltura
  #   ports:
  #     - 80

  thumbor:
    image: apsl/thumbor
    ports:
      - 8000

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    environment:
      ALLOWED_DOMAINS: '.*'
      FORCE_HTTPS: 'false'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - storage:/srv/storage
      - ./conf.d:/etc/nginx/conf.d
      - ./index.html:/srv/storage/index.html
    depends_on:
      - admin-legacy
      - live2vod
      - thumbor

volumes:
  ssl_data:
  storage:
